### ISSUE TITLE
"Something wrong"

### ISSUE THREAD

**Issue by Big-al** [EricPucho/FirebaseXamarinForms#2]
I tested this project today, edited the connection both for Basepath and Authkey but i keep getting the "Something wrong" message. Is this deprecated by now´, or should it still work?

**Comment by EricPucho** [comment]
Let's me see ;-)

**Comment by Big-al** [comment]
Added it here: https://github.com/Big-al/XamarinFirebaseTest/invitations 
Set up a test database in firebase - check the folder labeled "CONNECTIONDATA" for auth and link to make sure i set it up correctly :-)

**Comment by Big-al** [comment]
@EricPucho did you have the same issue?

**Comment by EricPucho** [comment]
You must allow users to connect (Database -> Rules)

{ "rules": { ".read": true, ".write": true } }

**Comment by Big-al** [comment]
That was already set like this:
![screenshot_1](https://user-images.githubusercontent.com/7080878/39404118-892ae16c-4b8c-11e8-9434-5f40a1e5f453.png)

**Comment by Big-al** [comment]
Tried with another firebase database - still no connection

**Comment by EricPucho** [comment]
Hi, I just create new project and test, nothing goes wrong.

Can you give me your Twitter?

**Comment by EricPucho** [comment]
Check your BasePath : "https://*****.firebaseio.com/" in DATA section, before RULES tab.

 And change in code 

 IFirebaseConfig config = new FirebaseConfig
            {
                AuthSecret = "",
                BasePath = "https://******.firebaseio.com/"
            };
            IFirebaseClient client = new FirebaseClient(config);

**Comment by Big-al** [comment]
@AlanKristensen is my twitter - if you check the project on this repo all of that is set up correct i believe:

Basepath is correct at: https://fir-xamarinforms-d4c3f.firebaseio.com/

Rules of the db set to:
{
  "rules": {
    ".read": true,
    ".write": true
  }
}

**Comment by Big-al** [comment]
Any ideas?
